/* A recursive-descent parser generated by peg 0.1.18 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 22
#line 1 "./vm.leg"


/*
FOR storing the web text
This is a global variable that will hold the web text.

*/

#ifdef __EMSCRIPTEN__
char *WEBTEXT 	   = 0;
int   WEBTEXT_SIZE = 0;
int   WEBTEXT_POS  = 0;

int store(const char* msg) {
	printf("store called with msg: %s\n", msg);
	if(WEBTEXT){
		printf("Freeing previous WEBTEXT\n");
		free(WEBTEXT); // Free previous content if any
	}
	WEBTEXT_SIZE = strlen(msg);
	if (WEBTEXT_SIZE == 0) {
		printf("WEBTEXT_SIZE is 0, returning\n");
		return 0;
	}
    WEBTEXT = strdup(msg);
	WEBTEXT_POS = 0; 
	printf("end of store function\n");
	return 1;
}

int getchar_from_text() {
    if (!WEBTEXT || WEBTEXT[WEBTEXT_POS] == '\0') {
        return -1; // EOF の代わり
    }
    return WEBTEXT[WEBTEXT_POS++];
}

// This function is used to read characters from the web text.
#define getchar getchar_from_text
#endif








// comment out one or both of the next two lines to disable tagged integers and/or floats

#define TAGINT	1			// tag bits value for Integer  ........1
#define TAGFLT	2			// tag bits value for Float    .......10

#define TAGBITS 2			// how many bits to use for tag bits
#define TAGMASK ((1 << TAGBITS) - 1)	// mask to extract just the tag bits

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <assert.h>
#include <stdarg.h>
#include <setjmp.h>
#include <stdint.h>
#include <unistd.h>

void fatal(char *msg, ...)
{
    va_list ap;
    va_start(ap, msg);
    fprintf(stderr, "\n");
    vfprintf(stderr, msg, ap);
    fprintf(stderr, "\n");
    va_end(ap);
    exit(1);
}

union Object;
typedef union Object Object;
typedef Object *oop; // ordinary object pointer

oop nil   = 0;
oop false = 0;
oop true  = 0;

enum Type {
    /*  0 */ Undefined = 0,
    /*  1 */ Integer, Float, Symbol, Pair, Array, Closure, Function,
    /*  8 */ Binop, Unyop, GetVar, SetVar, GetArray, SetArray,
    /* 14 */ Call, Return, Break, Continue,
    /* 18 */ Print, If, While, Block,
};

enum binop { ADD, SUB, MUL, DIV, MOD, LT, LE, GE, GT, EQ, NE, };
enum unyop { NEG, NOT, };

struct Undefined { enum Type _type; };
struct Integer 	 { enum Type _type;  int _value;  };
struct Symbol  	 { enum Type _type;  char *name;  oop value; };
struct Pair  	 { enum Type _type;  oop a, b; };
struct Array  	 { enum Type _type;  oop *elements;  int size, capacity; };
struct Closure 	 { enum Type _type;  oop function, environment; };
struct Function	 { enum Type _type;  oop parameters, body, code; };
struct Binop   	 { enum Type _type;  enum binop op;  oop lhs, rhs; };
struct Unyop   	 { enum Type _type;  enum unyop op;  oop rhs; };
struct GetVar  	 { enum Type _type;  oop id; };
struct SetVar  	 { enum Type _type;  oop id; oop rhs; };
struct GetArray	 { enum Type _type;  oop array, index; };
struct SetArray	 { enum Type _type;  oop array, index, value; };
struct Call 	 { enum Type _type;  oop function, arguments; };
struct Return 	 { enum Type _type;  oop value; };
struct Break 	 { enum Type _type; };
struct Continue	 { enum Type _type; };
struct Print   	 { enum Type _type;  oop arguments; };
struct If      	 { enum Type _type;  oop condition, statement1, statement2; };
struct While   	 { enum Type _type;  oop condition, statement; };
struct Block   	 { enum Type _type;  oop *statements;  int size; };

union Object {
    enum   Type     _type;
    struct Integer  Integer;
    struct Symbol   Symbol;
    struct Pair     Pair;
    struct Array    Array;
    struct Closure  Closure;
    struct Function Function;
    struct Binop    Binop;
    struct Unyop    Unyop;
    struct GetVar   GetVar;
    struct SetVar   SetVar;
    struct GetArray GetArray;
    struct SetArray SetArray;
    struct Call     Call;
    struct Return   Return;
    struct Break    Break;
    struct Continue Continue;
    struct Print    Print;
    struct If       If;
    struct While    While;
    struct Block    Block;
};

int getType(oop o)
{
#if TAGINT
    if ((((intptr_t)o) & TAGMASK) == TAGINT) return Integer;
#endif
#if TAGFLT
    if ((((intptr_t)o) & TAGMASK) == TAGFLT) return Float;
#endif
    return o->_type;
}

oop _check(oop node, enum Type type, char *file, int line)
{
    if (getType(node) != type) {
	fprintf(stderr, "\n%s:%d: expected type %d got type %d\n", file, line, type, getType(node));
	exit(1);
    }
    return node;
}

#define get(PTR, TYPE, FIELD)	(_check((PTR), TYPE, __FILE__, __LINE__)->TYPE.FIELD)

int nobj = 0;

oop _newObject(size_t size, enum Type type)
{
    nobj++;
    oop node = calloc(1, size);
    node->_type = type;
    return node;
}

#define newObject(TYPE)	_newObject(sizeof(struct TYPE), TYPE)

oop newInteger(int value)
{
#if TAGINT
    return (oop)(((intptr_t)value << TAGBITS) | TAGINT);
#else
    oop node = newObject(Integer);
    node->Integer._value = value;
    return node;
#endif
}

int Integer_value(oop obj)
{
#if TAGINT
    assert(Integer == getType(obj));
    return (intptr_t)obj >> TAGBITS;
#else
    return get(obj, Integer,_value);
#endif
}

oop newFloat(double value)
{
#if TAGFLT
    union { double d;  intptr_t i; } u = { .d = value };
    return (oop)(((intptr_t)u.i & ~TAGMASK) | TAGFLT);
#else
    oop node = newObject(Float);
    node->Float._value = value;
    return node;
#endif
}

double Float_value(oop obj)
{
#if TAGFLT
    assert(Float == getType(obj));
    union { intptr_t i;  double d; } u = { .i = (intptr_t)obj };
    return u.d;
#else
    return get(obj, Float,_value);
#endif
}

oop newSymbol(char *name)
{
    oop sym = newObject(Symbol);
    sym->Symbol.name  = strdup(name);
    sym->Symbol.value = false;
    return sym;
}

oop *symbols = 0;
int nsymbols = 0;
 
oop intern(char *name)
{
    // binary search for existing symbol
    int lo = 0, hi = nsymbols - 1;
    while (lo <= hi) {
	int mid = (lo + hi) / 2;
	int cmp = strcmp(name, get(symbols[mid], Symbol,name));
	if      (cmp < 0) hi = mid - 1;
	else if (cmp > 0) lo = mid + 1;
	else    return symbols[mid];
    }
    symbols   = realloc(symbols,   sizeof(*symbols)   * (nsymbols + 1));
    memmove(symbols + lo + 1,
	    symbols + lo,
	    sizeof(*symbols) * (nsymbols++ - lo));
    return symbols[lo] = newSymbol(name);
}

void printlnObject(oop node, int indent);

oop newPair(oop a, oop b)
{
    oop obj = newObject(Pair);
    obj->Pair.a = a;
    obj->Pair.b = b;
    return obj;
}

oop newArray(int size)
{
    oop obj = newObject(Array);
    if (size) {
	obj->Array.elements = calloc(size, sizeof(oop));
	obj->Array.size     = size;
	obj->Array.capacity = size;
	for (int i = 0;  i < size;  ++i)
	    obj->Array.elements[i]= nil;
    }
    return obj;
}

oop Array_grow(oop array)
{
    int size  = get(array, Array,size);
    int cap   = get(array, Array,capacity);
    oop *elts = get(array, Array,elements);
    while (size >= cap) {
	cap = cap ? cap * 2 : 4;
	elts = realloc(elts, sizeof(*elts) * cap);
    }
    get(array, Array,capacity) = cap;
    get(array, Array,elements) = elts;
    return array;
}

oop Array_append(oop array, oop element)
{
    int size = get(array, Array,size);
    if (size >= get(array, Array,capacity)) Array_grow(array);
    get(array, Array,elements)[size++] = element;
    get(array, Array,size) = size;
    return element;
}

oop Array_last(oop array)
{
    int size = get(array, Array,size);
    if (size == 0) fatal("last: array is empty");
    return get(array, Array,elements)[size-1];
}

oop Array_pop(oop array)
{
    int size = get(array, Array,size);
    if (size == 0) fatal("pop: array is empty");
    oop element = get(array, Array,elements)[--size];
    get(array, Array,size) = size;
    return element;
}

oop newClosure(oop func, oop env)
{
    oop node = newObject(Closure);
    node->Closure.function    = func;
    node->Closure.environment = env;
    return node;
}

oop newFunction(oop parameters, oop body)
{
    oop node = newObject(Function);
    node->Function.parameters = parameters;
    node->Function.body       = body;
    node->Function.code       = nil;
    return node;
}

oop newBinop(enum binop op, oop lhs, oop rhs)
{
    oop node = newObject(Binop);
    node->Binop.op  = op;
    node->Binop.lhs = lhs;
    node->Binop.rhs = rhs;
    return node;
}

oop newUnyop(enum unyop op, oop rhs)
{
    oop node = newObject(Unyop);
    node->Unyop.op  = op;
    node->Unyop.rhs = rhs;
    return node;
}

oop newGetVar(oop id)
{
    oop node = newObject(GetVar);
    node->GetVar.id = id;
    return node;
}

oop newSetVar(oop id, oop rhs)
{
    oop node = newObject(SetVar);
    node->SetVar.id  = id;
    node->SetVar.rhs = rhs;
    return node;
}

oop newGetArray(oop array, oop index)
{
    oop node = newObject(GetArray);
    node->GetArray.array = array;
    node->GetArray.index = index;
    return node;
}

oop newSetArray(oop array, oop index, oop value)
{
    oop node = newObject(SetArray);
    node->SetArray.array = array;
    node->SetArray.index = index;
    node->SetArray.value = value;
    return node;
}

oop newCall(oop arguments, oop function)
{
    oop node = newObject(Call);
    node->Call.arguments = arguments;
    node->Call.function  = function;
    return node;
}

oop newReturn(oop value)
{
    oop node = newObject(Return);
    node->Return.value = value;
    return node;
}

oop newBreak(void)
{
    return newObject(Break);
}

oop newContinue(void)
{
    return newObject(Continue);
}

oop newPrint(oop arguments)
{
    oop node = newObject(Print);
    node->Print.arguments = arguments;
    return node;
}

oop newIf(oop condition, oop s1, oop s2)
{
    oop node = newObject(If);
    node->If.condition = condition;
    node->If.statement1 = s1;
    node->If.statement2 = s2;
    return node;
}

oop newWhile(oop condition, oop s)
{
    oop node = newObject(While);
    node->While.condition = condition;
    node->While.statement = s;
    return node;
}

oop newBlock(void)
{
    oop node = newObject(Block);
    node->Block.statements = 0;
    node->Block.size = 0;
    return node;
}

void Block_append(oop b, oop s)
{
    oop *ss = get(b, Block,statements);
    int  sz = get(b, Block,size);
    ss = realloc(ss, sizeof(oop) * (sz + 1));
    ss[sz++] = s;
    get(b, Block,statements) = ss;
    get(b, Block,size) = sz;
}

void printlnObject(oop node, int indent)
{
    printf("%*s", indent*2, "");
    switch (getType(node)) {
	case Undefined:	printf("nil\n");				break;
	case Integer:	printf("%d\n", Integer_value(node));		break;

	case Symbol:	printf("%s\n", get(node, Symbol,name));		break;
	case Pair: {
	    printf("Pair\n");
	    printlnObject(get(node, Pair,a), indent+1);
	    printlnObject(get(node, Pair,b), indent+1);
	    break;
	}
	case Array: {
	    printf("Array\n");
	    for (int i = 0;  i < get(node, Array,size);  ++i)
		printlnObject(get(node, Array,elements)[i], indent+1);
	    break;
	}
	case Closure: {
	    printf("Closure\n");
	    printlnObject(get(node, Closure,function), indent+1);
	    break;
	}
	case Function: {
	    printf("function()\n");
	    printlnObject(get(node, Function,parameters), indent+2);
	    printlnObject(get(node, Function,body), indent+1);
	    break;
	}
	case Binop: {
	    switch (get(node, Binop,op)) {
		case NE:  printf("NE\n"); break;
		case EQ:  printf("EQ\n"); break;
		case LT:  printf("LT\n"); break;
		case LE:  printf("LE\n"); break;
		case GE:  printf("GE\n"); break;
		case GT:  printf("GT\n"); break;
		case ADD: printf("ADD\n"); break;
		case SUB: printf("SUB\n"); break;
		case MUL: printf("MUL\n"); break;
		case DIV: printf("DIV\n"); break;
		case MOD: printf("MOD\n"); break;
		default:  assert(!"this cannot happen");
	    }
	    printlnObject(get(node, Binop,lhs), indent+1);
	    printlnObject(get(node, Binop,rhs), indent+1);
	    break;
	}
	case Unyop: {
	    switch (get(node, Unyop,op)) {
		case NEG: printf("NEG\n"); break;
		case NOT: printf("NOT\n"); break;
		default:  assert(!"this cannot happen");
	    }
	    printlnObject(get(node, Unyop,rhs), indent+1);
	    break;
	}
	case GetVar: {
	    printf("GetVar %s\n", get(get(node, GetVar,id), Symbol,name));
	    break;
	}
	case SetVar: {
	    printf("SetVar %s\n", get(get(node, SetVar,id), Symbol,name));
	    printlnObject(get(node, SetVar,rhs), indent+1);
	    break;
	}
	case GetArray: {
	    printf("GetArray\n");
	    printlnObject(get(node, GetArray,array), indent+1);
	    printlnObject(get(node, GetArray,index), indent+1);
	    break;
	}
	case SetArray: {
	    printf("SetArray\n");
	    printlnObject(get(node, SetArray,array), indent+1);
	    printlnObject(get(node, SetArray,index), indent+1);
	    printlnObject(get(node, SetArray,value), indent+1);
	    break;
	}
	case Call: {
	    printf("Call\n");
	    printlnObject(get(node, Call,function), indent+1);
	    printlnObject(get(node, Call,arguments), indent+1);
	    break;
	}
	case Return: {
	    printf("Return\n");
	    printlnObject(get(node, Return,value), indent+1);
	    break;
	}
	case Break: {
	    printf("Break\n");
	    break;
	}
	case Continue: {
	    printf("Continue\n");
	    break;
	}
	case Print: {
	    printf("Print\n");
	    printlnObject(get(node, Print,arguments), indent+1);
	    break;
	}
	case If: {
	    printf("If\n");
	    printlnObject(get(node, If,condition), indent+1);
	    printlnObject(get(node, If,statement1), indent+1);
	    printlnObject(get(node, If,statement2), indent+1);
	    break;
	}
	case While: {
	    printf("While\n");
	    printlnObject(get(node, While,condition), indent+1);
	    printlnObject(get(node, While,statement), indent+1);
	    break;
	}
	case Block: {
	    printf("Block...\n");
	    break;
	}
	default:
	    assert(!"this cannot happen");
    }
}

void println(oop obj)	{ printlnObject(obj, 0); }

void print(oop node)
{
    switch (getType(node)) {
	case Undefined:	printf("nil");				break;
	case Integer:	printf("%d", Integer_value(node));	break;
	case Float:	printf("%f", Float_value(node));	break;
	case Symbol:	printf("%s", get(node, Symbol,name));	break;
	default:	println(node);				break;
    }
}

#define YYSTYPE oop

YYSTYPE result;


#ifndef YY_MALLOC
#define YY_MALLOC(C, N)		malloc(N)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(C, P, N)	realloc(P, N)
#endif
#ifndef YY_FREE
#define YY_FREE(C, P)		free(P)
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YYRELEASE
#define YYRELEASE	yyrelease
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yy->__begin= yy->__pos, 1)
#endif
#ifndef YY_END
#define YY_END		( yy->__end= yy->__pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif
#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_SIZE
#define YY_BUFFER_SIZE 1024
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *yy, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *__buf;
  int       __buflen;
  int       __pos;
  int       __limit;
  char     *__text;
  int       __textlen;
  int       __begin;
  int       __end;
  int       __textmax;
  yythunk  *__thunks;
  int       __thunkslen;
  int       __thunkpos;
  YYSTYPE   __;
  YYSTYPE  *__val;
  YYSTYPE  *__vals;
  int       __valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#ifndef YY_INPUT
#define YY_INPUT(yy, buf, result, max_size)		\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext _yyctx= { 0, 0 };
yycontext *yyctx= &_yyctx;
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#endif

YY_LOCAL(int) yyrefill(yycontext *yy)
{
  int yyn;
  while (yy->__buflen - yy->__pos < 512)
    {
      yy->__buflen *= 2;
      yy->__buf= (char *)YY_REALLOC(yy, yy->__buf, yy->__buflen);
    }
#ifdef YY_CTX_LOCAL
  YY_INPUT(yy, (yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#else
  YY_INPUT((yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#endif
  if (!yyn) return 0;
  yy->__limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *yy)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  ++yy->__pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *yy, int c)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  if ((unsigned char)yy->__buf[yy->__pos] == c)
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *yy, const char *s)
{
  int yysav= yy->__pos;
  while (*s)
    {
      if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
      if (yy->__buf[yy->__pos] != *s)
        {
          yy->__pos= yysav;
          return 0;
        }
      ++s;
      ++yy->__pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *yy, unsigned char *bits)
{
  int c;
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  c= (unsigned char)yy->__buf[yy->__pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *yy, yyaction action, int begin, int end)
{
  while (yy->__thunkpos >= yy->__thunkslen)
    {
      yy->__thunkslen *= 2;
      yy->__thunks= (yythunk *)YY_REALLOC(yy, yy->__thunks, sizeof(yythunk) * yy->__thunkslen);
    }
  yy->__thunks[yy->__thunkpos].begin=  begin;
  yy->__thunks[yy->__thunkpos].end=    end;
  yy->__thunks[yy->__thunkpos].action= action;
  ++yy->__thunkpos;
}

YY_LOCAL(int) yyText(yycontext *yy, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yy->__textlen < (yyleng + 1))
	{
	  yy->__textlen *= 2;
	  yy->__text= (char *)YY_REALLOC(yy, yy->__text, yy->__textlen);
	}
      memcpy(yy->__text, yy->__buf + begin, yyleng);
    }
  yy->__text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *yy)
{
  int pos;
  for (pos= 0;  pos < yy->__thunkpos;  ++pos)
    {
      yythunk *thunk= &yy->__thunks[pos];
      int yyleng= thunk->end ? yyText(yy, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yy->__text));
      thunk->action(yy, yy->__text, yyleng);
    }
  yy->__thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *yy)
{
  if ((yy->__limit -= yy->__pos))
    {
      memmove(yy->__buf, yy->__buf + yy->__pos, yy->__limit);
    }
  yy->__begin -= yy->__pos;
  yy->__end -= yy->__pos;
  yy->__pos= yy->__thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *yy, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(yy);
      yyCommit(yy);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *yy, char *text, int count)
{
  yy->__val += count;
  while (yy->__valslen <= yy->__val - yy->__vals)
    {
      long offset= yy->__val - yy->__vals;
      yy->__valslen *= 2;
      yy->__vals= (YYSTYPE *)YY_REALLOC(yy, yy->__vals, sizeof(YYSTYPE) * yy->__valslen);
      yy->__val= yy->__vals + offset;
    }
}
YY_LOCAL(void) yyPop(yycontext *yy, char *text, int count)   { yy->__val -= count; }
YY_LOCAL(void) yySet(yycontext *yy, char *text, int count)   { yy->__val[count]= yy->__; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yy, yythunkpos0)

YY_RULE(int) yy_blank(yycontext *yy); /* 22 */
YY_RULE(int) yy_alnum(yycontext *yy); /* 21 */
YY_RULE(int) yy_alpha(yycontext *yy); /* 20 */
YY_RULE(int) yy_integer(yycontext *yy); /* 19 */
YY_RULE(int) yy_RPAR(yycontext *yy); /* 18 */
YY_RULE(int) yy_LPAR(yycontext *yy); /* 17 */
YY_RULE(int) yy_PCENT(yycontext *yy); /* 16 */
YY_RULE(int) yy_SLASH(yycontext *yy); /* 15 */
YY_RULE(int) yy_STAR(yycontext *yy); /* 14 */
YY_RULE(int) yy_value(yycontext *yy); /* 13 */
YY_RULE(int) yy_MINUS(yycontext *yy); /* 12 */
YY_RULE(int) yy_PLUS(yycontext *yy); /* 11 */
YY_RULE(int) yy_mul(yycontext *yy); /* 10 */
YY_RULE(int) yy_add(yycontext *yy); /* 9 */
YY_RULE(int) yy_ASSIGN(yycontext *yy); /* 8 */
YY_RULE(int) yy_id(yycontext *yy); /* 7 */
YY_RULE(int) yy_assign(yycontext *yy); /* 6 */
YY_RULE(int) yy_eol(yycontext *yy); /* 5 */
YY_RULE(int) yy_SEMI(yycontext *yy); /* 4 */
YY_RULE(int) yy_expr(yycontext *yy); /* 3 */
YY_RULE(int) yy__(yycontext *yy); /* 2 */
YY_RULE(int) yy_start(yycontext *yy); /* 1 */

YY_ACTION(void) yy_1_id(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_id\n"));
  {
#line 624
   __ = intern(yytext) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_integer(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_integer\n"));
  {
#line 622
   __ = newInteger(atoi(yytext)) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_value(yycontext *yy, char *yytext, int yyleng)
{
#define i yy->__val[-1]
#define lhs yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_value\n"));
  {
#line 617
   __ = newGetVar(i) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef i
#undef lhs
}
YY_ACTION(void) yy_1_value(yycontext *yy, char *yytext, int yyleng)
{
#define i yy->__val[-1]
#define lhs yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_value\n"));
  {
#line 615
   __ = lhs ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef i
#undef lhs
}
YY_ACTION(void) yy_4_mul(yycontext *yy, char *yytext, int yyleng)
{
#define rhs yy->__val[-1]
#define lhs yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_mul\n"));
  {
#line 610
   __ = lhs ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef rhs
#undef lhs
}
YY_ACTION(void) yy_3_mul(yycontext *yy, char *yytext, int yyleng)
{
#define rhs yy->__val[-1]
#define lhs yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_mul\n"));
  {
#line 609
   lhs = newBinop(MOD, lhs, rhs) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef rhs
#undef lhs
}
YY_ACTION(void) yy_2_mul(yycontext *yy, char *yytext, int yyleng)
{
#define rhs yy->__val[-1]
#define lhs yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_mul\n"));
  {
#line 608
   lhs = newBinop(DIV, lhs, rhs) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef rhs
#undef lhs
}
YY_ACTION(void) yy_1_mul(yycontext *yy, char *yytext, int yyleng)
{
#define rhs yy->__val[-1]
#define lhs yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_mul\n"));
  {
#line 607
   lhs = newBinop(MUL, lhs, rhs) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef rhs
#undef lhs
}
YY_ACTION(void) yy_3_add(yycontext *yy, char *yytext, int yyleng)
{
#define rhs yy->__val[-1]
#define lhs yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_add\n"));
  {
#line 605
   __ = lhs ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef rhs
#undef lhs
}
YY_ACTION(void) yy_2_add(yycontext *yy, char *yytext, int yyleng)
{
#define rhs yy->__val[-1]
#define lhs yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_add\n"));
  {
#line 604
   lhs = newBinop(SUB, lhs, rhs) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef rhs
#undef lhs
}
YY_ACTION(void) yy_1_add(yycontext *yy, char *yytext, int yyleng)
{
#define rhs yy->__val[-1]
#define lhs yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_add\n"));
  {
#line 603
   lhs = newBinop(ADD, lhs, rhs) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef rhs
#undef lhs
}
YY_ACTION(void) yy_1_assign(yycontext *yy, char *yytext, int yyleng)
{
#define x yy->__val[-1]
#define i yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_assign\n"));
  {
#line 599
   __ = newSetVar(i, x) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef x
#undef i
}
YY_ACTION(void) yy_4_start(yycontext *yy, char *yytext, int yyleng)
{
#define x yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_start\n"));
  {
#line 594
   fatal("syntax error: %s", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef x
}
YY_ACTION(void) yy_3_start(yycontext *yy, char *yytext, int yyleng)
{
#define x yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_start\n"));
  {
#line 593
   printf("\n%d objects allocated\n", nobj); result = 0; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef x
}
YY_ACTION(void) yy_2_start(yycontext *yy, char *yytext, int yyleng)
{
#define x yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_start\n"));
  {
#line 592
   result = false; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef x
}
YY_ACTION(void) yy_1_start(yycontext *yy, char *yytext, int yyleng)
{
#define x yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_start\n"));
  {
#line 591
   result = x; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef x
}

YY_RULE(int) yy_blank(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "blank"));
  {  int yypos2= yy->__pos, yythunkpos2= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\046\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l3;  goto l2;
  l3:;	  yy->__pos= yypos2; yy->__thunkpos= yythunkpos2;  if (!yymatchString(yy, "//")) goto l1;
  l4:;	
  {  int yypos5= yy->__pos, yythunkpos5= yy->__thunkpos;
  {  int yypos6= yy->__pos, yythunkpos6= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\044\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l6;  goto l5;
  l6:;	  yy->__pos= yypos6; yy->__thunkpos= yythunkpos6;
  }  if (!yymatchDot(yy)) goto l5;  goto l4;
  l5:;	  yy->__pos= yypos5; yy->__thunkpos= yythunkpos5;
  }
  }
  l2:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "blank", yy->__buf+yy->__pos));
  return 1;
  l1:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "blank", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_alnum(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "alnum"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l7;
  yyprintf((stderr, "  ok   %s @ %s\n", "alnum", yy->__buf+yy->__pos));
  return 1;
  l7:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "alnum", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_alpha(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "alpha"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l8;
  yyprintf((stderr, "  ok   %s @ %s\n", "alpha", yy->__buf+yy->__pos));
  return 1;
  l8:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "alpha", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_integer(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "integer"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l9;
#undef yytext
#undef yyleng
  }  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l9;
  l10:;	
  {  int yypos11= yy->__pos, yythunkpos11= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l11;  goto l10;
  l11:;	  yy->__pos= yypos11; yy->__thunkpos= yythunkpos11;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l9;
#undef yytext
#undef yyleng
  }  if (!yy__(yy)) goto l9;  yyDo(yy, yy_1_integer, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "integer", yy->__buf+yy->__pos));
  return 1;
  l9:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "integer", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_RPAR(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "RPAR"));  if (!yymatchChar(yy, ')')) goto l12;  if (!yy__(yy)) goto l12;
  yyprintf((stderr, "  ok   %s @ %s\n", "RPAR", yy->__buf+yy->__pos));
  return 1;
  l12:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "RPAR", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LPAR(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LPAR"));  if (!yymatchChar(yy, '(')) goto l13;  if (!yy__(yy)) goto l13;
  yyprintf((stderr, "  ok   %s @ %s\n", "LPAR", yy->__buf+yy->__pos));
  return 1;
  l13:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LPAR", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PCENT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PCENT"));  if (!yymatchChar(yy, '%')) goto l14;  if (!yy__(yy)) goto l14;
  yyprintf((stderr, "  ok   %s @ %s\n", "PCENT", yy->__buf+yy->__pos));
  return 1;
  l14:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PCENT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_SLASH(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "SLASH"));  if (!yymatchChar(yy, '/')) goto l15;  if (!yy__(yy)) goto l15;
  yyprintf((stderr, "  ok   %s @ %s\n", "SLASH", yy->__buf+yy->__pos));
  return 1;
  l15:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "SLASH", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_STAR(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "STAR"));  if (!yymatchChar(yy, '*')) goto l16;  if (!yy__(yy)) goto l16;
  yyprintf((stderr, "  ok   %s @ %s\n", "STAR", yy->__buf+yy->__pos));
  return 1;
  l16:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "STAR", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_value(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "value"));
  {  int yypos18= yy->__pos, yythunkpos18= yy->__thunkpos;  if (!yy_LPAR(yy)) goto l19;  if (!yy_expr(yy)) goto l19;  yyDo(yy, yySet, -2, 0);  if (!yy_RPAR(yy)) goto l19;  yyDo(yy, yy_1_value, yy->__begin, yy->__end);  goto l18;
  l19:;	  yy->__pos= yypos18; yy->__thunkpos= yythunkpos18;  if (!yy_integer(yy)) goto l20;  goto l18;
  l20:;	  yy->__pos= yypos18; yy->__thunkpos= yythunkpos18;  if (!yy_id(yy)) goto l17;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_2_value, yy->__begin, yy->__end);
  }
  l18:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "value", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l17:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "value", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_MINUS(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "MINUS"));  if (!yymatchChar(yy, '-')) goto l21;  if (!yy__(yy)) goto l21;
  yyprintf((stderr, "  ok   %s @ %s\n", "MINUS", yy->__buf+yy->__pos));
  return 1;
  l21:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "MINUS", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PLUS(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PLUS"));  if (!yymatchChar(yy, '+')) goto l22;  if (!yy__(yy)) goto l22;
  yyprintf((stderr, "  ok   %s @ %s\n", "PLUS", yy->__buf+yy->__pos));
  return 1;
  l22:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PLUS", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_mul(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "mul"));  if (!yy_value(yy)) goto l23;  yyDo(yy, yySet, -2, 0);
  l24:;	
  {  int yypos25= yy->__pos, yythunkpos25= yy->__thunkpos;
  {  int yypos26= yy->__pos, yythunkpos26= yy->__thunkpos;  if (!yy_STAR(yy)) goto l27;  if (!yy_value(yy)) goto l27;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_mul, yy->__begin, yy->__end);  goto l26;
  l27:;	  yy->__pos= yypos26; yy->__thunkpos= yythunkpos26;  if (!yy_SLASH(yy)) goto l28;  if (!yy_value(yy)) goto l28;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_2_mul, yy->__begin, yy->__end);  goto l26;
  l28:;	  yy->__pos= yypos26; yy->__thunkpos= yythunkpos26;  if (!yy_PCENT(yy)) goto l25;  if (!yy_value(yy)) goto l25;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_3_mul, yy->__begin, yy->__end);
  }
  l26:;	  goto l24;
  l25:;	  yy->__pos= yypos25; yy->__thunkpos= yythunkpos25;
  }  yyDo(yy, yy_4_mul, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "mul", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l23:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "mul", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_add(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "add"));  if (!yy_mul(yy)) goto l29;  yyDo(yy, yySet, -2, 0);
  l30:;	
  {  int yypos31= yy->__pos, yythunkpos31= yy->__thunkpos;
  {  int yypos32= yy->__pos, yythunkpos32= yy->__thunkpos;  if (!yy_PLUS(yy)) goto l33;  if (!yy_mul(yy)) goto l33;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_add, yy->__begin, yy->__end);  goto l32;
  l33:;	  yy->__pos= yypos32; yy->__thunkpos= yythunkpos32;  if (!yy_MINUS(yy)) goto l31;  if (!yy_mul(yy)) goto l31;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_2_add, yy->__begin, yy->__end);
  }
  l32:;	  goto l30;
  l31:;	  yy->__pos= yypos31; yy->__thunkpos= yythunkpos31;
  }  yyDo(yy, yy_3_add, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "add", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l29:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "add", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ASSIGN(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ASSIGN"));  if (!yymatchChar(yy, '=')) goto l34;
  {  int yypos35= yy->__pos, yythunkpos35= yy->__thunkpos;  if (!yymatchChar(yy, '=')) goto l35;  goto l34;
  l35:;	  yy->__pos= yypos35; yy->__thunkpos= yythunkpos35;
  }  if (!yy__(yy)) goto l34;
  yyprintf((stderr, "  ok   %s @ %s\n", "ASSIGN", yy->__buf+yy->__pos));
  return 1;
  l34:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ASSIGN", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_id(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "id"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l36;
#undef yytext
#undef yyleng
  }  if (!yy_alpha(yy)) goto l36;
  l37:;	
  {  int yypos38= yy->__pos, yythunkpos38= yy->__thunkpos;  if (!yy_alnum(yy)) goto l38;  goto l37;
  l38:;	  yy->__pos= yypos38; yy->__thunkpos= yythunkpos38;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l36;
#undef yytext
#undef yyleng
  }  if (!yy__(yy)) goto l36;  yyDo(yy, yy_1_id, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "id", yy->__buf+yy->__pos));
  return 1;
  l36:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "id", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_assign(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "assign"));
  {  int yypos40= yy->__pos, yythunkpos40= yy->__thunkpos;  if (!yy_id(yy)) goto l41;  yyDo(yy, yySet, -2, 0);  if (!yy_ASSIGN(yy)) goto l41;  if (!yy_assign(yy)) goto l41;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_assign, yy->__begin, yy->__end);  goto l40;
  l41:;	  yy->__pos= yypos40; yy->__thunkpos= yythunkpos40;  if (!yy_add(yy)) goto l39;
  }
  l40:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "assign", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l39:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "assign", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_eol(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "eol"));  if (!yymatchClass(yy, (unsigned char *)"\000\044\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l42;
  yyprintf((stderr, "  ok   %s @ %s\n", "eol", yy->__buf+yy->__pos));
  return 1;
  l42:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eol", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_SEMI(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "SEMI"));  if (!yymatchChar(yy, ';')) goto l43;  if (!yy__(yy)) goto l43;
  yyprintf((stderr, "  ok   %s @ %s\n", "SEMI", yy->__buf+yy->__pos));
  return 1;
  l43:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "SEMI", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_expr(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "expr"));  if (!yy_assign(yy)) goto l44;
  yyprintf((stderr, "  ok   %s @ %s\n", "expr", yy->__buf+yy->__pos));
  return 1;
  l44:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "expr", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy__(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "_"));
  l46:;	
  {  int yypos47= yy->__pos, yythunkpos47= yy->__thunkpos;  if (!yy_blank(yy)) goto l47;  goto l46;
  l47:;	  yy->__pos= yypos47; yy->__thunkpos= yythunkpos47;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "_", yy->__buf+yy->__pos));
  return 1;
}
YY_RULE(int) yy_start(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "start"));
  {  int yypos49= yy->__pos, yythunkpos49= yy->__thunkpos;  if (!yy__(yy)) goto l50;  if (!yy_expr(yy)) goto l50;  yyDo(yy, yySet, -1, 0);  if (!yy_SEMI(yy)) goto l50;  yyDo(yy, yy_1_start, yy->__begin, yy->__end);  goto l49;
  l50:;	  yy->__pos= yypos49; yy->__thunkpos= yythunkpos49;  if (!yy__(yy)) goto l51;  if (!yy_SEMI(yy)) goto l51;  yyDo(yy, yy_2_start, yy->__begin, yy->__end);  goto l49;
  l51:;	  yy->__pos= yypos49; yy->__thunkpos= yythunkpos49;
  {  int yypos53= yy->__pos, yythunkpos53= yy->__thunkpos;  if (!yymatchDot(yy)) goto l53;  goto l52;
  l53:;	  yy->__pos= yypos53; yy->__thunkpos= yythunkpos53;
  }  yyDo(yy, yy_3_start, yy->__begin, yy->__end);  goto l49;
  l52:;	  yy->__pos= yypos49; yy->__thunkpos= yythunkpos49;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l48;
#undef yytext
#undef yyleng
  }
  l54:;	
  {  int yypos55= yy->__pos, yythunkpos55= yy->__thunkpos;
  {  int yypos56= yy->__pos, yythunkpos56= yy->__thunkpos;  if (!yy_eol(yy)) goto l56;  goto l55;
  l56:;	  yy->__pos= yypos56; yy->__thunkpos= yythunkpos56;
  }
  {  int yypos57= yy->__pos, yythunkpos57= yy->__thunkpos;  if (!yymatchDot(yy)) goto l55;  yy->__pos= yypos57; yy->__thunkpos= yythunkpos57;
  }  if (!yymatchDot(yy)) goto l55;  goto l54;
  l55:;	  yy->__pos= yypos55; yy->__thunkpos= yythunkpos55;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l48;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_4_start, yy->__begin, yy->__end);
  }
  l49:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "start", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l48:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "start", yy->__buf+yy->__pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *yy);

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  if (!yyctx->__buflen)
    {
      yyctx->__buflen= YY_BUFFER_SIZE;
      yyctx->__buf= (char *)YY_MALLOC(yyctx, yyctx->__buflen);
      yyctx->__textlen= YY_BUFFER_SIZE;
      yyctx->__text= (char *)YY_MALLOC(yyctx, yyctx->__textlen);
      yyctx->__thunkslen= YY_STACK_SIZE;
      yyctx->__thunks= (yythunk *)YY_MALLOC(yyctx, sizeof(yythunk) * yyctx->__thunkslen);
      yyctx->__valslen= YY_STACK_SIZE;
      yyctx->__vals= (YYSTYPE *)YY_MALLOC(yyctx, sizeof(YYSTYPE) * yyctx->__valslen);
      yyctx->__begin= yyctx->__end= yyctx->__pos= yyctx->__limit= yyctx->__thunkpos= 0;
    }
  yyctx->__begin= yyctx->__end= yyctx->__pos;
  yyctx->__thunkpos= 0;
  yyctx->__val= yyctx->__vals;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_start);
}

YY_PARSE(yycontext *) YYRELEASE(yycontext *yyctx)
{
  if (yyctx->__buflen)
    {
      yyctx->__buflen= 0;
      YY_FREE(yyctx, yyctx->__buf);
      YY_FREE(yyctx, yyctx->__text);
      YY_FREE(yyctx, yyctx->__thunks);
      YY_FREE(yyctx, yyctx->__vals);
    }
  return yyctx;
}

#endif
#line 650 "./vm.leg"
;



jmp_buf *nlrs = 0;
int nnlrs     = 0;
oop nlrval    = 0;


#define nlrReturn(N) longjmp(nlrs[nnlrs-1], N)

#define nlrPop() --nnlrs


#undef BINOP



// virtual machine

enum {
    iHALT, iPUSH,
    iADD, iSUB, iMUL, iDIV, iMOD,
    iGETVAR, iSETVAR,
	iMKSPACE,
	iPRINT,
};






struct IntArray{
	int *elements;
	int size, capacity;
};
typedef struct IntArray *iptr;

iptr stack = 0;

iptr intArray_init()
{
	struct IntArray *a = malloc(sizeof(struct IntArray));
	a->elements = (int*)malloc(sizeof(int) * 4);
	a->size     = 0;
	a->capacity = 4;
	return a;
}

void intArray_append(struct IntArray *a, int value)
{
	if (a->size >= a->capacity) {
		a->capacity = a->capacity ? a->capacity * 2 : 4;
		a->elements = realloc(a->elements, sizeof(int) * a->capacity);
	}
	a->elements[a->size++] = value;
}
int intArray_pop(struct IntArray *a)
{
	if (a->size == 0) fatal("pop: stack is empty");
	return a->elements[--a->size];
}
int intArray_last(struct IntArray *a)
{
	if (a->size == 0) fatal("last: stack is empty");
	return a->elements[a->size - 1];
}


#define push(O)	intArray_append(stack, O)
#define pop()	intArray_pop(stack)
#define top()	intArray_last(stack)


iptr execute(iptr prog,iptr stack)
{
    int* code = prog->elements;
	int size = prog->size;

    int* webanswer = NULL;
	int webanswersize = 0;

    int pc = 0;
# define fetch()	code[pc++]

    for (;;) {
	int op = fetch();
	int l = 0, r = 0;
	switch (op) {
		case iMKSPACE:{
			printf("iMKSPACE\n");
			int nvars = fetch();
			for (int i = 0;  i < nvars;  ++i) {
				push(0); // reserve space for local variables
			}
			continue;
		}
	    case iHALT:{
			printf("iHALT\n");
			free(stack->elements); // free the stack elements
			free(stack); // free the stack itself
			
			iptr ans = malloc(sizeof(struct IntArray));
			ans->elements = webanswer;
			ans->size = webanswersize;
			printf("webanswer\n");
			for (int i = 0;  i < webanswersize;  ++i) {
				printf("%d = %d\n", i, webanswer[i]);
			}
			return ans; // return the answer
		}
	    case iADD:printf("iADD\n");  r = pop();  l = pop();  push(l + r);  continue;
	    case iSUB:printf("iSUB\n");  r = pop();  l = pop();  push(l - r);  continue;
	    case iMUL:printf("iMUL\n");  r = pop();  l = pop();  push(l * r);  continue;
	    case iDIV:printf("iDIV\n");  r = pop();  l = pop();  push(l / r);  continue;
	    case iMOD:printf("iMOD\n");  r = pop();  l = pop();  push(l % r);  continue;
	    case iGETVAR:{
			printf("iGETVAR\n");
			int symIndex = fetch(); // need to change
			push(stack->elements[symIndex]);
			continue;
		}	    
	    case iSETVAR:{
			printf("iSETVAR\n");
			int symIndex = fetch();//need to change
			stack->elements[symIndex] = top();
			continue;
		}	
		case iPUSH:{
		printf("iPUSH\n");
			l = fetch();
			push(l);
			continue;
		}
		case iPRINT:{
			printf("iPRINT\n");
			printf("ans = %d\n", top());
			if(webanswer){
				printf("webanswer already exists, appending to it\n");
				webanswer = (int*)realloc(webanswer, sizeof(int) * (webanswersize + 1));
				webanswer[webanswersize++] = pop();
			}
			else{
				printf("webanswer does not exist, creating new one\n");
				webanswer = (int*)malloc(sizeof(int));
				webanswer[0] = pop();
				webanswersize = 1;
			}
			continue;
		}
		continue;
	    default:fatal("illegal instruction %d", op);
	}
	}
# undef fetch
# undef push
# undef pop
    return 0; // should never reach here
}

// AST->VM compiler

iptr compile();
oop *variables = 0;
int nvariables = 0;

int insertVariable(oop sym)
{
	// linear search for existing variable
	for (int i = 0;  i < nvariables;  ++i)
	if (variables[i] == sym) return i;
	variables = realloc(variables, sizeof(*variables) * (nvariables + 1));
	variables[nvariables++] = sym;
	return nvariables - 1;
}
int searchVariable(oop sym)
{
	// linear search for existing variable
	for (int i = 0;  i < nvariables;  ++i)
	if (variables[i] == sym) return i;
	return -1;
}

void emitL (iptr array, oop object) 	  { intArray_append(array, Integer_value(object)); }
void emitI (iptr array, int i     ) 	  { intArray_append(array, i); }
void emitII(iptr array, int i, int j)      { emitI(array, i); emitI(array, j); }
void emitIL(iptr array, int i, oop object) { emitI(array, i); emitL(array, object); }

void emitOn(iptr prog, oop ast)
{
    switch (getType(ast)) {
		case Undefined:
		case Integer:{
			emitIL(prog, iPUSH, ast);
			return;
		}
		case Binop:{
			emitOn(prog, get(ast, Binop,lhs));
			emitOn(prog, get(ast, Binop,rhs));
			switch (get(ast, Binop,op)) {
			case ADD: emitI(prog, iADD);  return;
			case SUB: emitI(prog, iSUB);  return;
			case MUL: emitI(prog, iMUL);  return;
			case DIV: emitI(prog, iDIV);  return;
			case MOD: emitI(prog, iMOD);  return;
			default:printf("error\n");return;
			}
			break;
		}
		case GetVar: {
			oop sym = get(ast, GetVar,id);
			int symIndex = searchVariable(sym);
			if (symIndex < 0) {
				printf("variable %s not found\n", get(sym, Symbol,name));
				exit(1);
			}
			emitII(prog, iGETVAR, symIndex);
			return;
		}
		case SetVar: {
			oop sym = get(ast, SetVar,id);
			oop rhs = get(ast, SetVar,rhs);
			emitOn(prog, rhs);
			int symIndex = insertVariable(sym);
			emitII(prog, iSETVAR, symIndex);
			return;
		}
		default:break;
    }
    fatal("emitOn: unimplemented emitter for type %d", getType(ast));
}

void printCode(iptr code){
	for (int i = 0;  i < code->size;  ++i) {
		int op = code->elements[i];
		switch (op) {
			case iHALT: printf("%03d: HALT\n", i); break;
			case iPUSH: ++i;printf("%03d: LOAD %03d\n", i-1, code->elements[i]); break;
			case iADD:  printf("%03d: ADD\n", i); break;
			case iSUB:  printf("%03d: SUB\n", i); break;
			case iMUL:  printf("%03d: MUL\n", i); break;
			case iDIV:  printf("%03d: DIV\n", i); break;
			case iMOD:  printf("%03d: MOD\n", i); break;
			case iGETVAR:
			++i;
			printf("%03d: GETVAR %03d\n", i-1, code->elements[i]);
			break;
			case iSETVAR:
			++i;
			printf("%03d: SETVAR %03d\n", i-1, code->elements[i]);
			break;
			case iMKSPACE:
			++i;
			printf("%03d: MKSPACE %03d\n", i-1, code->elements[i]);
			break;
			case iPRINT:
			printf("%03d: PRINT\n", i);
			break;
			default:
			printf("%03d: UNKNOWN %03d\n", i, op);
		}
	}
	printf("\n");
}

iptr compile()
{
    iptr prog = intArray_init();

	emitII(prog, iMKSPACE, 0); // reserve space for local variables

	// compile the AST into the program code
	int line = 1;
	while(yyparse()){
		if (result == 0) {
			break;
		}
		emitOn(prog, result);
		emitI(prog, iPRINT); // print the result
		printf("line %3d: compile one statement %d\n",++line, prog->size);
	}
    emitI (prog, iHALT); // end of program
	prog->elements[1] = nvariables; // store number of variables
#ifndef __EMSCRIPTEN__
	printf("\ncompile finished, %d statements, code size %d bytes\n\n", line, 4 * prog->size);
#endif
    return prog;
}

/* --------------------------------- *
	 * WebVM関連のコード
 * --------------------------------- */


iptr webcode = 0;     // コンパイル結果を保持するグローバル変数
iptr webresults = 0;  // VMの実行結果を保持するグローバル変数

// web_compile_size() と web_compile() は現状のままで良いと仮定します。
int web_compile_size() {
    // 以前のコンパイル結果や実行結果が残っていれば解放
    if (webcode) {
        printf("Freeing previous webcode\n");
        free(webcode);
        webcode = 0;
    }
    if (webresults) {
		printf("Freeing previous webresults\n");
        free(webresults);
        webresults = 0;
    }
	printf("call web_compile_size\n");
    webcode = compile();
	printf("end of web_compile_size %d\n", webcode ? webcode->size : 0);
    return webcode ? webcode->size : 0;
}

int* web_compile() {
	printf("call web_compile\n");
	printCode(webcode);
	printf("end of web_compile %d\n",webcode ? webcode->size : 0);
    return webcode ? webcode->elements : NULL;
}

// VMを実行し、結果の「サイズ」を返すように修正
// 引数としてコードのポインタとサイズを受け取る
int web_vm_execute_size(int* code_ptr, int code_size) {
	printf("call web_vm_execute_size\n");
    // 以前の実行結果が残っていれば解放
    if (webresults) {
        free(webresults);
        webresults = 0;
    }
    iptr prog = malloc(sizeof(struct IntArray)); // IntArrayの構造を仮定
    if (!prog) return 0; // メモリ確保失敗

    prog->elements = code_ptr;
    prog->size = code_size;

    // 正しく設定した prog をVMに渡して実行
    webresults = execute(prog, intArray_init());

    // execute関数がprog自体を消費しない場合、ここで解放
    // (prog->elementsはJS側のメモリなので解放しない)
	printf("end of web_vm_execute_size %d\n", webresults ? webresults->size : 0);
    return webresults ? webresults->size : 0;
}

// VMの実行結果のデータポインタを返す
// (web_vm_execute_size によって webresults は設定済みのはず)
int* web_vm_execute() {
	printf("call web_vm_execute\n");
	printf("web_vm_execute: webresults size = %d\n", webresults ? webresults->size : 0);
    return webresults ? webresults->elements : NULL;
}

/* --------------------------------- *
	 * WebVM関連のコード
 * --------------------------------- */

#ifndef __EMSCRIPTEN__
int main(int argc, char **argv)
{
#if TAGFLT
    assert(sizeof(double) == sizeof(intptr_t));
#endif

    nil   = newObject(Undefined);
    false = newInteger(0);
    true  = newInteger(1);

    nlrval = nil;


	iptr code = compile();
	printCode(code);
    stack = intArray_init();
	execute(code, stack);
}
#endif

